theme = "ayu_evolve"

[editor]
line-number = "relative"
mouse = true
popup-border = "all"
rulers = [80, 100]
true-color = true
color-modes = true
editor-config = true
text-width = 80
cursorline = true
completion-trigger-len = 1

completion-replace = true
completion-timeout = 100

end-of-line-diagnostics = "hint"

[editor.inline-diagnostics]
cursor-line = "warning"

[editor.search]
smart-case = true

[editor.cursor-shape]
insert = "block"
normal = "block"
select = "underline"

[editor.indent-guides]
render = true

[editor.lsp]
display-inlay-hints = true

[editor.file-picker]
hidden = false

[editor.statusline]
left = [
  "mode",
  "file-name",
]
right = [
  "spinner",
  "diagnostics",
  "spacer",
  "file-encoding",
  "file-line-ending",
  "file-type",
  "spacer",
  "position-percentage",
  "position",
]

[editor.whitespace.render]
# render = "all"
space = "none"
tabl = "all"
nbsp = "none"
nnbsp = "none"
newline = "none"

[editor.auto-save]
focus-lost = true
after-delay.enable = true

[editor.gutters]
layout = ["diff", "diagnostics", "line-numbers", "spacer"]

[keys.normal]
"X" = "select_line_above"
"G" = "goto_file_end"
"0" = "goto_line_start"
"$" = "goto_line_end"
"F" = ":reflow"

[keys.insert]
j = {k = "normal_mode"}

